name: Deploy Examples

on:
  push:
    branches: [ "main", "workflow-tests" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jetli/wasm-bindgen-action@v0.1.0
    - uses: actions/checkout@v3
    - name: Build
      run: |
        rustup target add wasm32-unknown-unknown
        cargo build --release --target wasm32-unknown-unknown --examples
        wasm-bindgen --out-dir ./wasm-out --no-typescript --target web target/wasm32-unknown-unknown/release/examples/slider.wasm
        
